batch_size: 32
network_type: "fully_connected"
input_size: 4
epochs: 100
loss: "sparse_categorical_crossentropy"
output_activation: "softmax"
learning_rate: 0.001
train_eval_period: 20
dev_eval_period: 1

network_config:
  lstm:
    layers: [[32, 2], [16, 1]]
    dropout: 0.1
    activation: 'relu'
  cnn:
    layers: [[32,3],[32,3],[32,3]]
    dropout: 0.1
    activation: 'relu'
  fully_connected:
    hidden_nodes: [256]
    dropout: 0.05
    activation: 'relu'

train: "data/train.xlsx"
test: "data/test.xlsx"
dev: "data/dev.xlsx"
csv_file: "results/accuracy.csv"
