training_type: "DL"
network_type: "fully_connected"
batch_size: 32
input_size: 4
epochs: 100
loss: "sparse_categorical_crossentropy"
output_activation: "softmax"
learning_rate: 0.001
train_eval_period: 20
dev_eval_period: 1
num_classes: 2

network_config:
  lstm:
    layers: [[32, 2], [16, 1]]
    dropout: 0.1
    activation: 'relu'
  cnn:
    layers: [[32,3],[32,3],[32,3]]
    dropout: 0.1
    activation: 'relu'
  fully_connected:
    hidden_nodes: [256]
    dropout: 0.05
    activation: 'relu'
  SVM:
    kernel: 'linear'
    c: 1
  logistic_regression:
    c: 1
  KNN:
    k: 5
  NB:
    type: 'Gaussian'

train: "data/train.xlsx"
test: "data/test.xlsx"
dev: "data/dev.xlsx"
csv_file: "results/accuracy.csv"
save_model: True
model_path: "models/model"
